const state={view:"overview",assets:["BTCUSDT","ETHUSDT"],timeframe:"1H",mode:"research",autoExecution:false,panels:JSON.parse(localStorage.getItem("orion-panels")||'{"equity":true,"signals":true,"research":true,"risk":true,"markets":true,"activity":true}')};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const panelNames={equity:"Equity & performance",signals:"Active signals",research:"Research status",risk:"Risk controls",markets:"Market watch",activity:"Recent activity"};
function save(){localStorage.setItem("orion-panels",JSON.stringify(state.panels))}
function chips(){
  $("#asset-filters").innerHTML=["BTCUSDT","ETHUSDT","EURUSD","GBPUSD","NAS100","US30"].map(x=>'<button class="chip '+(state.assets.includes(x)?'active':'')+'" data-asset="'+x+'">'+x+"</button>").join("");
  $("#tf-filters").innerHTML=["15M","1H","4H","1D"].map(x=>'<button class="chip '+(state.timeframe===x?'active':'')+'" data-tf="'+x+'">'+x+"</button>").join("");
  $$("[data-asset]").forEach(b=>b.onclick=()=>{const x=b.dataset.asset;state.assets=state.assets.includes(x)?state.assets.filter(a=>a!==x):[...state.assets,x];chips();render()});
  $$("[data-tf]").forEach(b=>b.onclick=()=>{state.timeframe=b.dataset.tf;chips();render()});
}
function stat(title,value,sub,cls=""){return '<div class="card stat"><div class="card-title"><h3>'+title+'</h3></div><div class="big '+cls+'">'+value+'</div><div class="sub">'+sub+"</div></div>"}
function renderOverview(){let c='<div class="grid">';if(state.panels.equity)c+=stat("Portfolio","$10,000","Research baseline • live capital not connected");if(state.panels.signals)c+=stat("Signals","—","Waiting for validated market run","neutral");if(state.panels.research)c+=stat("Research","RUNNING","BTCUSDT + ETHUSDT • 2024–2026","neutral");if(state.panels.risk)c+=stat("Risk / trade","0.50%","Current engine configuration");
if(state.panels.equity)c+='<section class="card wide"><div class="card-title"><h3>Equity curve</h3><span class="muted">No live results yet</span></div><div class="chart">'+Array.from({length:42},(_,i)=>'<div class="bar" style="height:'+(30+((i*17)%55))+'%"></div>').join("")+"</div></section>";
if(state.panels.risk)c+='<section class="card side"><div class="card-title"><h3>Risk guardrails</h3><span class="pill">SAFE</span></div>'+[['Mode','RESEARCH'],['Auto execution','DISABLED'],['ATR stop','1.5×'],['Reward target','2.0×'],['Min signal score','0.0']].map(r=>'<div class="metric-row"><span class="muted">'+r[0]+'</span><strong>'+r[1]+"</strong></div>").join("")+"</section>";
if(state.panels.markets)c+='<section class="card full"><div class="card-title"><h3>Market watch</h3><span class="muted">'+state.timeframe+" • "+state.assets.length+" selected</span></div><table class="table"><thead><tr><th>Instrument</th><th>Regime</th><th>Signal</th><th>State</th></tr></thead><tbody>'+state.assets.map((x,i)=>'<tr><td><strong>'+x+'</strong></td><td class="muted">Awaiting scan</td><td>—</td><td><span class="pill">RESEARCH</span></td></tr>').join("")+"</tbody></table></section>";
if(state.panels.activity)c+='<section class="card full"><div class="card-title"><h3>Activity</h3></div><div class="empty">ORION will stream research runs, signals, orders, fills, errors and system events here.</div></section>";return c+"</div>"}
function render(){const title=state.view[0].toUpperCase()+state.view.slice(1);$("#page-title").textContent=title;$("#mode-badge").textContent=state.mode.toUpperCase();let html="";if(state.view==="overview")html=renderOverview();else html='<div class="card full"><div class="card-title"><h3>'+title+'</h3><span class="pill">FOUNDATION READY</span></div><div class="empty">This module is wired into the ORION dashboard shell. Its live data adapter will be connected as the research/execution APIs mature.</div></div>';$("#view").innerHTML=html}
function customize(){ $("#panel-toggles").innerHTML=Object.entries(panelNames).map(([k,v])=>'<div class="toggle-row"><span>'+v+'</span><button class="switch '+(state.panels[k]?'on':'')+'" data-panel="'+k+'"><i></i></button></div>').join("");$$("[data-panel]").forEach(b=>b.onclick=()=>{const k=b.dataset.panel;state.panels[k]=!state.panels[k];b.classList.toggle("on",state.panels[k])});$("#customize-dialog").showModal()}
$$(".nav-item").forEach(b=>b.onclick=()=>{$$(".nav-item").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.view=b.dataset.view;render()});$("#customize").onclick=customize;$("#refresh").onclick=()=>{render();$("#refresh").textContent="✓";setTimeout(()=>$("#refresh").textContent="↻",700)};$("#customize-dialog").addEventListener("close",()=>{save();render()});chips();render();